### PR TITLE
feat: Returns last updated trackable objects from object tracker

### PR DESCRIPTION
**Pull request by nicolexirakia**
## Description

This MR updates the object tracker to return the following: 

- `addon_object.shared["trackable_objects"]` is the filtered list of trackable objects that were seen and tracked on the current frame
- `addon_object.shared["trackable_objects_history"]` the full history of currently alive trackable objects (some of them were not detected or inactive in the current frame)

In turn, this also updates the speed estimator, where the speed is calculated over the full history of trackable objects, however, only the speed and action of the last updated trackable objects (`addon_object.shared["trackable_objects"]`) is returned and communicated with visionx. This assumes a stable and constant speed for all tracked objects, even if they were not successfully detected on the current frame. The objects that won't reappear after a while will be deregistered from the history, however, if the object detection failed for n frames to detect an object, its current speed is still roughly calculated by considering a constant speed during the missed frames. 

### How to test 

- Run visionx on people detection along with the object tracker and speed estimator 
- Run people detection with `make run`

### What to expect 

In the current frame, if eg. 12 bounding boxes were detected, the results of speed estimation should equal to these 12 bounding boxes. For instance: 

```json
"addon_object.inference.extra"{
   "tracked_objects":0,
   "current_speed":{
      "0":0.6868643942827857,
      "1":0.0,
      "2":0.16209876027949038,
      "3":0.06329108462482329,
      "4":0.10552309389693124,
      "5":0.27291471769811937,
      "6":0.034956838481066926,
      "7":0.1898732538744699,
      "8":0.20799426146789335,
      "9":0.3788415479672548,
      "10":0.10552309389693124,
      "11":0.14598043117297102
   },
   "current_action":{
      "0":"standing",
      "1":"standing",
      "2":"standing",
      "3":"standing",
      "4":"standing",
      "5":"standing",
      "6":"standing",
      "7":"standing",
      "8":"standing",
      "9":"standing",
      "10":"standing",
      "11":"standing"
   }
}
```

Where the full `trackable_objects_history` contained 13 objects: 

```json
{
   "0":{
      "object_id":0
   },
   "1":{
      "object_id":1
   },
   "2":{
      "object_id":2
   },
   "3":{
      "object_id":3
   },
   "4":{
      "object_id":4
   },
   "5":{
      "object_id":5
   },
   "6":{
      "object_id":6
   },
   "7":{
      "object_id":7
   },
   "8":{
      "object_id":8
   },
   "9":{
      "object_id":9
   },
   "10":{
      "object_id":10
   },
   "11":{
      "object_id":11
   },
   "12":{
      "object_id":12
   }
}
```

### CODE REVIEW

**Comment by gujjs** [comment]
If you want to make some data accessible for visionx you should store it in inference object. shared dict is to make data accessible to other addons

**Comment by gujjs** [comment]
```yaml

addons:
  tracking:
    bidirectional_mode: true
    bidirectional_threshold: 150
    class: vsdkx.addon.tracking.processor.TrackerProcessor
    distance_threshold: 500
    max_disappeared: 10
    min_appearance: 1
  speed:
    class: vsdkx.addon.tracking.speed_estimation_processor.SpeedEstimationProcessor
    person_action: True
    camera_length: 7
    lens_dimension: 2000 # optional if horizontal and vertical degrees are set
    focal_length: 2700 # optional if horizontal and vertical degrees are set
    camera_horizontal_degrees: 0 # optional if lens dimension and focal length are set
    camera_vertical_degrees: 0 # optional if lens dimension and focal length are set
    fps: 25
model:
  class: vsdkx.model.yolo_torch.driver.YoloTorchDriver
  debug: false
  profile: yolo-torch
  settings:
    conf_thresh: 0.5
    device: cpu
    iou_thresh: 0.4

```

config used for testing

**Comment by nicolexirakia** [comment]
> ```yaml
> addons:
>   tracking:
>     bidirectional_mode: true
>     bidirectional_threshold: 150
>     class: vsdkx.addon.tracking.processor.TrackerProcessor
>     distance_threshold: 500
>     max_disappeared: 10
>     min_appearance: 1
>   speed:
>     class: vsdkx.addon.tracking.speed_estimation_processor.SpeedEstimationProcessor
>     person_action: True
>     camera_length: 7
>     lens_dimension: 2000 # optional if horizontal and vertical degrees are set
>     focal_length: 2700 # optional if horizontal and vertical degrees are set
>     camera_horizontal_degrees: 0 # optional if lens dimension and focal length are set
>     camera_vertical_degrees: 0 # optional if lens dimension and focal length are set
>     fps: 25
> model:
>   class: vsdkx.model.yolo_torch.driver.YoloTorchDriver
>   debug: false
>   profile: yolo-torch
>   settings:
>     conf_thresh: 0.5
>     device: cpu
>     iou_thresh: 0.4
> ```
> 
> config used for testing

that's not going to work since speed estimation and trajectory estimation have moved to their own repos. Use the proposed configs from corresponding MRs for these two add-ons.

**Comment by gujjs** [comment]
when inference observed manually, `current_speed` keys seem to have parity with `current_action`, however I did some simple assertion statement that made it 100 % certain that it is so.

we could have some unit test like this here now or in the future
```py
assert set(result["extra"]["current_speed"].keys()) == set(result["extra"]["current_action"].keys())
```

just an idea

**Review by gujjs — APPROVED** [review]

**Pull request merged**
