### PR TITLE
fix: add 's' to trackable_object key

### PR DESCRIPTION
**Pull request by gujjs**

### CODE REVIEW

**Comment by gujjs** [comment]
this MR changes the key that is written in `extra` dictionary. the `trackable_objects` stored in extra dict is later accessed by zoning and group addons

**Comment by nicolexirakia** [comment]
Just tested this (locally) on dog detection with zoning and the dictionary result we send to visionx is pretty much the same as before. Here is the output with some additional logging:

```
Tracker received 1 bounding boxes
Object tracker results: Trackable objects {0: {'object_id': 0}} Tracked objects 0
Zoning processor results {'zone_0': {'Person': 0, 'objects_entered': {'Person': 0}, 'objects_exited': {'Person': 0}}, 'rest': {'Person': 0}}
```

**Comment by nicolexirakia** [comment]
Some additional logging on the results of 4 consecutive frames:

```
Tracker received 0 bounding boxes
Object tracker results: Trackable objects {} Tracked objects 0
Zoning processor results {'zone_0': {'Person': 0, 'objects_entered': {'Person': 0}, 'objects_exited': {'Person': 0}}, 'rest': {'Person': 0}}
Tracker received 0 bounding boxes
Object tracker results: Trackable objects {} Tracked objects 0
Zoning processor results {'zone_0': {'Person': 0, 'objects_entered': {'Person': 0}, 'objects_exited': {'Person': 0}}, 'rest': {'Person': 0}}
Tracker received 1 bounding boxes
Object tracker results: Trackable objects {0: {'object_id': 0}} Tracked objects 0
Zoning processor results {'zone_0': {'Person': 0, 'objects_entered': {'Person': 0}, 'objects_exited': {'Person': 1}}, 'rest': {'Person': 0}}
Tracker received 1 bounding boxes
Object tracker results: Trackable objects {0: {'object_id': 0}} Tracked objects 0
Zoning processor results {'zone_0': {'Person': 0, 'objects_entered': {'Person': 0}, 'objects_exited': {'Person': 0}}, 'rest': {'Person': 1}}
```

This is a good example where everything seems to be working. Not sure why we get 0 results in all zones on the first example I showed you. But good to keep it in mind while testing.

**Comment by gujjs** [comment]
@nicolexirakia here, you can see it's not zero, 

```
Tracker received 1 bounding boxes
Object tracker results: Trackable objects {0: {'object_id': 0}} Tracked objects 0
Zoning processor results {'zone_0': {'Person': 0, 'objects_entered': {'Person': 0}, 'objects_exited': {'Person': 1}}, 'rest': {'Person': 0}}
Tracker received 1 bounding boxes
Object tracker results: Trackable objects {0: {'object_id': 0}} Tracked objects 0
Zoning processor results {'zone_0': {'Person': 0, 'objects_entered': {'Person': 0}, 'objects_exited': {'Person': 0}}, 'rest': {'Person': 1}}

```

SO I think boxes are not detected, where it's all 0 ? it would be more helpful if you look at boxes as well. it might be the case that it's working fine, just not inferencing boxes on that frame.

**Comment by gujjs** [comment]
```
Tracker received 1 bounding boxes
Object tracker results: Trackable objects {0: {'object_id': 0}} Tracked objects 0
Zoning processor results {'zone_0': {'Person': 0, 'objects_entered': {'Person': 0}, 'objects_exited': {'Person': 0}}, 'rest': {'Person': 0}}

```

I don't know what's wrong here :(

**Review by nicolexirakia — APPROVED** [review]

**Pull request merged**
